import type { Metadata } from "next";
import { Geist, Geist_Mono, Parkinsans, Orbitron } from "next/font/google";
import "./globals.css";
import Footer from "./components/shared/Footer";
import Navbar from "./components/shared/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const parkinsans = Parkinsans({
  variable: "--font-parkinsans",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TasteHub",
  description: "Generated by Betopia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${parkinsans.variable} ${orbitron.variable} antialiased`}
      >
        <div className="sticky top-0 z-50">
          <div className="backdrop-blur-xs ">
            <Navbar />
          </div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
